FROM ubuntu:14.04
MAINTAINER jacknorthrup "madhatterstamps@gmail.com"

# Install Dev Libs
RUN apt-get update && apt-get install -y \
    build-essential \
    gfortran \
    g++ \
    cmake \
    software-properties-common \
    git \
    wget \
    curl \
    nano \
    xz-utils \
    file \
    locales \
    locate \
    htop \
    tar \
    zip


RUN apt-get install -y \
    libatlas-base-dev \
    libboost-all-dev \
    libflann-dev \
    libgsl0-dev \
    libeigen3-dev \
    libgoogle-perftools-dev \
    terminator

RUN apt-get install -y \
    libfreetype6-dev \
    libxft-dev \
    python-dev \
    python-pip

# Install Python libs
RUN pip install numpy
RUN pip install scipy
RUN pip install matplotlib
RUN pip install pandas
RUN pip install tornado
RUN piup install pillow

# Intall some basic GUI libs
RUN apt-get install -y \
        dbus-x11 dmz-cursor-theme fonts-dejavu fonts-liberation hicolor-icon-theme \
        libgtk2.0-0 libdbus-glib-1-2 libxt6 libexif12 \
        libgl1-mesa-glx libgl1-mesa-dri

RUN update-locale LC_MESSAGES=POSIX

# Install some sound libs
RUN apt-get install -y \
    pulseaudio \
    libcanberra-gtk3-0 \
    libcanberra-gtk-module \
    libcanberra-gtk3-module \
    libasound2

RUN update-locale LANG=C.UTF-8

# Cleaning the environment
RUN apt-get clean autoclean

RUN apt-get autoremove -y

